[project]
name = "oulajnr forecast"
version = "1.0.0"
requires-python = ">=3.8"
license = {file = "LICENSE"}
dependencies = [
  "torch~=2.3",  # package was tested on 2.2
  "transformers~=4.21",
  "accelerate"
]

[project.optional-dependencies]
test = [
    "pytest~=7.5",
    "numpy~=1.21"
]

[tool.mypy]
ignore_missing_imports = true
